sudo: false
language: node_js
node_js:
- '0.8'
- '0.10'
- '0.12'
- '4'
- '6'
- '7'
matrix:
  fast_finish: true
cache:
  directories:
  - "$HOME/.npm"
  - "$HOME/.yarn-cache"
install:
- eval "$(curl -s https://raw.githubusercontent.com/balupton/awesome-travis/master/scripts/node-install.bash)"
before_script:
- eval "$(curl -s https://raw.githubusercontent.com/balupton/awesome-travis/master/scripts/node-verify.bash)"
after_success:
- eval "$(curl -s https://raw.githubusercontent.com/balupton/awesome-travis/master/scripts/node-publish.bash)"
notifications:
  slack:
    secure: UCD3cJpGd5EAFRfPKSOzSXeNQnEUfYcttbhKZsHKrevs+6wVbNW16BQKgzXPTBkO6mfp69Nv1yM8VWHWPs7UjmnpZ+tlRyUYPfKYY2TehngMlp2wJlDphB/CIYiIxxXNfCtVJuWq7esL44Lajyf7viKYT0H3wV9YGiwu8Gh1xx4=
  email:
    recipients:
      secure: uAHciGMVw2mEOMFBokHPUTaz/6wEr7S06Jik37UlitVtWf/8u3VAexgA8MnOhqIdoZYCpUk+1oCtEtSGweb1zCxhxOVMO5XMK3Kcn2pH7jFkhU1IS/iX1WvBPlEdu8GqUpg52QXOzDZBZI5YdQc6MyDogDC6xHJNVi2f/NlLKPQ=
